"use server";

import { ActionResponse } from "@/types";
import { GoogleGenAI } from "@google/genai";

export async function analyzeResumeWithAI(
  resumeText: string, 
  jobDescription: string
): Promise<ActionResponse<any>> {
  if (!process.env.GEMINI_API_KEY) {
    return { 
      success: false, 
      error: "Gemini API key is missing. Please add GEMINI_API_KEY to your .env.local file." 
    };
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    
    const prompt = `
    You are an expert ATS (Applicant Tracking System) and senior technical recruiter.
    Analyze the candidate's resume against the provided job description.
    
    Return ONLY a JSON object matching this exact schema:
    {
      "jobTitle": string, // the job title/role extracted from the job description (e.g., "Software Engineering Intern")
      "matchScore": number, // an integer from 0 to 100 representing how well the resume matches the JD
      "summary": string, // a 2-sentence summary of the candidate's fit
      "missingSkills": string[], // top 5 critical skills missing from the resume
      "matchingSkills": string[], // top 5 critical skills present in both
      "actionableFeedback": [
        {
          "category": string, // e.g., "Experience", "Formatting", "Impact"
          "suggestion": string // specific advice to improve the resume
        }
      ]
    }

    --- RESUME ---
    ${resumeText.substring(0, 10000)}

    --- JOB DESCRIPTION ---
    ${jobDescription.substring(0, 10000)}
    `;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    if (!response.text) {
      throw new Error("No response generated by the AI.");
    }

    const data = JSON.parse(response.text);
    return { success: true, data };
  } catch (error: any) {
    console.error("AI Analysis failed:", error);
    return { success: false, error: "Failed to analyze resume. Make sure your API key is correct." };
  }
}
